/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/sync/court-appearances/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    put: operations['syncCourtAppearance']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/court-appearance-movements/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    put: operations['syncCourtAppearanceMovement']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/resync/court-appearances/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    put: operations['resyncCourtAppearances']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/move/court-appearances': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    put: operations['moveCourtAppearances']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/court-appearances/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    get: operations['getCourtAppearance']
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    put: operations['applyAction']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/court-appearances': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    post: operations['findAppearancesForPrison']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/court-appearances/schedules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RO
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RW
     */
    post: operations['findAppearanceSchedules']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/people/{personIdentifier}/court-appearances': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    post: operations['findAppearancesForPerson']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/court-appearances/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    post: operations['scheduleCourtAppearance']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/court-appearances/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    get: operations['getCourtAppearance_1']
    put?: never
    post?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    delete: operations['deleteCourtAppearance']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/court-appearance-movements/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    get: operations['getCourtAppearanceMovement']
    put?: never
    post?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    delete: operations['deleteCourtAppearanceMovement']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconciliation/court-appearances/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__SYNC__RW
     */
    get: operations['getCourtAppearances']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/court-appearances/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RO
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RW
     */
    get: operations['appearance']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/court-appearances/{id}/movements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RO
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RW
     */
    get: operations['appearanceMovements']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/court-appearance-movements/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RO
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RW
     */
    get: operations['movement']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/court-appearances/{id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    get: operations['getAppearanceHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/court-appearance-reasons': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI
     */
    get: operations['getCourtAppearanceReasons']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CourtEvent: {
      /** Format: uuid */
      dpsId?: string | null
      prisonCodeAtTimeOfScheduling: string
      agyLocId: string
      /** Format: int64 */
      eventId?: number | null
      /** Format: date */
      eventDate: string
      startTime: string
      courtEventType: string
      eventStatus: string
      commentText?: string | null
      externalReferenceUrn?: string | null
    }
    SyncCourtEvent: {
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      occurredAt: string
      user: components['schemas']['SyncUser']
      courtEvent: components['schemas']['CourtEvent']
    }
    SyncUser: {
      username: string
      activeCaseloadId?: string | null
    }
    ReferenceId: {
      /** Format: uuid */
      id: string
    }
    CourtEventMovement: {
      /** Format: uuid */
      dpsId?: string | null
      /** Format: uuid */
      dpsCourtAppearanceScheduleId?: string
      /** Format: int64 */
      offenderBookId?: number
      /** Format: int32 */
      movementSeq?: number
      /** Format: date */
      movementDate: string
      movementTime: string
      movementReasonCode: string
      directionCode: string
      fromAgencyId: string
      toAgencyId: string
      commentText?: string | null
    }
    SyncCourtEventMovement: {
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      occurredAt: string
      user: components['schemas']['SyncUser']
      movement: components['schemas']['CourtEventMovement']
    }
    AtAndBy: {
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      at: string
      by: string
    }
    ResyncCourtEvent: {
      courtEvent: components['schemas']['CourtEvent']
      created: components['schemas']['AtAndBy']
      modified?: components['schemas']['AtAndBy'] | null
      movements: components['schemas']['ResyncCourtEventMovement'][]
    }
    ResyncCourtEventMovement: {
      movement: components['schemas']['CourtEventMovement']
      created: components['schemas']['AtAndBy']
      modified?: components['schemas']['AtAndBy'] | null
    }
    ResyncCourtEvents: {
      courtEvents: components['schemas']['ResyncCourtEvent'][]
      unscheduledMovements: components['schemas']['ResyncCourtEventMovement'][]
      isEmpty: boolean
    }
    CourtEventMapping: {
      /** Format: uuid */
      dpsId: string
      /** Format: int64 */
      eventId: number
      movements: components['schemas']['CourtMovementMapping'][]
    }
    CourtMovementMapping: {
      /** Format: uuid */
      dpsId: string
      /** Format: int64 */
      offenderBookId: number
      /** Format: int32 */
      movementSeq: number
    }
    ResyncResponse: {
      courtEvents: components['schemas']['CourtEventMapping'][]
      unscheduledMovements: components['schemas']['CourtMovementMapping'][]
    }
    MoveCourtEventRequest: {
      fromPersonIdentifier: string
      toPersonIdentifier: string
      scheduleIds: string[]
      unscheduledMovementIds: string[]
    }
    ChangeAppearanceComments: {
      type: 'ChangeAppearanceComments'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      comments?: string | null
      reason?: string | null
    })
    CompleteAppearance: {
      type: 'CompleteAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reason?: string | null
    })
    CourtAppearanceAction: {
      reason?: string
      type: string
    }
    ExpireAppearance: {
      type: 'ExpireAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reason?: string | null
    })
    RecategoriseAppearance: {
      type: 'RecategoriseAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reasonCode: string
      reason?: string | null
    })
    RelocateAppearance: {
      type: 'RelocateAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      courtCode: string
      reason?: string | null
    })
    RequestAppearanceByVideoLink: {
      type: 'RequestAppearanceByVideoLink'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reason?: string | null
    })
    RequestAppearanceInPerson: {
      type: 'RequestAppearanceInPerson'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reason?: string | null
    })
    RescheduleAppearance: {
      type: 'RescheduleAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      /** Format: date-time */
      start?: string | null
      /** Format: date-time */
      end?: string | null
      reason?: string | null
    })
    StartAppearance: {
      type: 'StartAppearance'
    } & (Omit<components['schemas']['CourtAppearanceAction'], 'type'> & {
      reason?: string | null
    })
    AuditHistory: {
      content: components['schemas']['AuditedAction'][]
    }
    AuditedAction: {
      user: components['schemas']['User']
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      occurredAt: string
      domainEvents: string[]
      reason?: string | null
      changes: components['schemas']['Change'][]
    }
    Change: {
      propertyName: string
      previous?: (string | number | boolean) | null
      change?: (string | number | boolean) | null
    }
    User: {
      username: string
      name: string
    }
    CourtAppearanceSearchRequest: {
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      status: ('SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'EXPIRED')[]
      reason: string[]
      courtCodes: string[]
      external?: boolean | null
      query?: string | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    AppearanceReason: {
      code: string
      description: string
      external: boolean
    }
    AppearanceStatus: {
      /** @enum {string} */
      code: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'EXPIRED'
      description: string
    }
    Court: {
      code: string
      name: string
    }
    CourtAppearanceResult: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      prison: components['schemas']['Prison']
      court: components['schemas']['Court']
      reason: components['schemas']['AppearanceReason']
      external: boolean
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      start: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      end?: string | null
      comments?: string | null
      status: components['schemas']['AppearanceStatus']
    }
    CourtAppearanceSearchResponse: {
      content: components['schemas']['CourtAppearanceResult'][]
      metadata: components['schemas']['PageMetadata']
    }
    PageMetadata: {
      /** Format: int64 */
      totalElements: number
    }
    Person: {
      personIdentifier: string
      firstName: string
      lastName: string
      prisonCode?: string | null
      cellLocation?: string | null
    }
    Prison: {
      code: string
      name: string
    }
    AppearanceScheduleSearchRequest: {
      personIdentifiers: string[]
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      status: ('SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'EXPIRED')[]
      reason: string[]
      courtCodes: string[]
      external?: boolean | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    CourtAppearanceSchedule: {
      /** Format: uuid */
      id: string
      personIdentifier: string
      court: components['schemas']['Court']
      reason: components['schemas']['AppearanceReason']
      external: boolean
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      start: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      end?: string | null
      status: components['schemas']['AppearanceStatus']
      detail: components['schemas']['Detail']
    }
    CourtAppearanceSchedules: {
      content: components['schemas']['CourtAppearanceSchedule'][]
      metadata: components['schemas']['PageMetadata']
    }
    Detail: {
      uiUrl: string
      requiredRoles: string[]
    }
    PersonAppearanceSearchRequest: {
      /** Format: date */
      start?: string | null
      /** Format: date */
      end?: string | null
      status: ('SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'EXPIRED')[]
      reason: string[]
      courtCodes: string[]
      external?: boolean | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    ScheduleCourtAppearance: {
      courtCode: string
      reasonCode: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      start: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      end?: string | null
      comments?: string | null
    }
    ReconciliationCourtEvent: {
      courtEvent: components['schemas']['CourtEvent']
      movements: components['schemas']['CourtEventMovement'][]
    }
    ReconciliationResponse: {
      courtEvents: components['schemas']['ReconciliationCourtEvent'][]
      unscheduledMovements: components['schemas']['CourtEventMovement'][]
    }
    IntegrationAppearance: {
      /** Format: uuid */
      id: string
      personIdentifier: string
      prisonCode: string
      courtCode: string
      reason: components['schemas']['IntegrationReason']
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      start: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      end?: string | null
      comments?: string | null
    }
    IntegrationReason: {
      code: string
      description: string
    }
    IntegrationResponseIntegrationAppearance: {
      data: components['schemas']['IntegrationAppearance']
      previousUrl?: string | null
      nextUrl?: string | null
    }
    IntegrationMovement: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      scheduleId?: string | null
      personIdentifier: string
      prisonCode: string
      courtCode: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      reason: components['schemas']['IntegrationReason']
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      occurredAt: string
      comments?: string | null
    }
    IntegrationResponseIntegrationMovement: {
      data: components['schemas']['IntegrationMovement']
      previousUrl?: string | null
      nextUrl?: string | null
    }
    IntegrationResponsesIntegrationMovement: {
      data: components['schemas']['IntegrationResponseIntegrationMovement'][]
      previousUrl?: string | null
    }
    Appearance: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      prison: components['schemas']['Prison']
      court: components['schemas']['Court']
      reason: components['schemas']['AppearanceReason']
      external: boolean
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      start: string
      /**
       * Format: date-time
       * @example 2026-05-13T12:44:08
       */
      end?: string | null
      comments?: string | null
      status: components['schemas']['AppearanceStatus']
    }
    CourtAppearanceReasons: {
      items: components['schemas']['AppearanceReason'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  syncCourtAppearance: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncCourtEvent']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceId']
        }
      }
    }
  }
  syncCourtAppearanceMovement: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncCourtEventMovement']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceId']
        }
      }
    }
  }
  resyncCourtAppearances: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResyncCourtEvents']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ResyncResponse']
        }
      }
    }
  }
  moveCourtAppearances: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveCourtEventRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getCourtAppearance: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Appearance']
        }
      }
    }
  }
  applyAction: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ChangeAppearanceComments']
          | components['schemas']['CompleteAppearance']
          | components['schemas']['ExpireAppearance']
          | components['schemas']['RecategoriseAppearance']
          | components['schemas']['RelocateAppearance']
          | components['schemas']['RequestAppearanceByVideoLink']
          | components['schemas']['RequestAppearanceInPerson']
          | components['schemas']['RescheduleAppearance']
          | components['schemas']['StartAppearance']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  findAppearancesForPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CourtAppearanceSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtAppearanceSearchResponse']
        }
      }
    }
  }
  findAppearanceSchedules: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppearanceScheduleSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtAppearanceSchedules']
        }
      }
    }
  }
  findAppearancesForPerson: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonAppearanceSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtAppearanceSearchResponse']
        }
      }
    }
  }
  scheduleCourtAppearance: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleCourtAppearance']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceId']
        }
      }
    }
  }
  getCourtAppearance_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtEvent']
        }
      }
    }
  }
  deleteCourtAppearance: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getCourtAppearanceMovement: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtEventMovement']
        }
      }
    }
  }
  deleteCourtAppearanceMovement: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getCourtAppearances: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReconciliationResponse']
        }
      }
    }
  }
  appearance: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['IntegrationResponseIntegrationAppearance']
        }
      }
    }
  }
  appearanceMovements: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['IntegrationResponsesIntegrationMovement']
        }
      }
    }
  }
  movement: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['IntegrationResponseIntegrationMovement']
        }
      }
    }
  }
  getAppearanceHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  getCourtAppearanceReasons: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CourtAppearanceReasons']
        }
      }
    }
  }
}
